#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2018 Aleksandr V. Piskunov <aleksandr.v.piskunov@gmail.com>.
# Copyright (C) 2015-2018 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
#
# 此看门狗脚本会尝试为不活跃的 AmneziaWG 对端重新解析主机名。
# 适用于动态 IP 经常变化的对端。
# 必须设置 persistent_keepalive，建议值为 25 秒。
#
# 使用 cron 每分钟运行一次：
# echo '* * * * * /usr/bin/wireguard_watchdog' >> /etc/crontabs/root

# shellcheck disable=SC1091,SC3043

. /lib/functions.sh

check_peer_activity() {
  local cfg="$1"
  local iface="$2"
  local disabled
  local public_key
  local endpoint_host
  local endpoint_port
  local persistent_keepalive
  local last_handshake
  local idle_seconds

  config_get_bool disabled "${cfg}" "disabled" 0
  config_get public_key    "${cfg}" "public_key"
  config_get endpoint_host "${cfg}" "endpoint_host"
  config_get endpoint_port "${cfg}" "endpoint_port"

  if [ "${disabled}" -eq 1 ]; then
    # 跳过已禁用的对端
    return 0
  fi

  persistent_keepalive=$(awg show "${iface}" persistent-keepalive | grep "${public_key}" | awk '{print $2}')

  # 仅处理已设置端点和保活的对端
  [ -z "${endpoint_host}" ] && return 0;
  if [ -z "${persistent_keepalive}" ] || [ "${persistent_keepalive}" = "off" ]; then return 0; fi

  # 跳过 IP 地址
  # 检查逻辑取自 packages/net/ddns-scripts/files/dynamic_dns_functions.sh
  local IPV4_REGEX="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}"
  local IPV6_REGEX="\(\([0-9A-Fa-f]\{1,4\}:\)\{1,\}\)\(\([0-9A-Fa-f]\{1,4\}\)\{0,1\}\)\(\(:[0-9A-Fa-f]\{1,4\}\)\{1,\}\)"
  local IPV4 IPV6
  IPV4="$(echo "${endpoint_host}" | grep -m 1 -o "$IPV4_REGEX$")"    # 不要将 0.0.0.0.example.com 中的部分识别为 IP
  IPV6="$(echo "${endpoint_host}" | grep -m 1 -o "$IPV6_REGEX")"
  [ -n "${IPV4}${IPV6}" ] && return 0;

  # 端点长时间无响应时重新解析其主机名
  last_handshake=$(awg show "${iface}" latest-handshakes | grep "${public_key}" | awk '{print $2}')
  [ -z "${last_handshake}" ] && return 0;
  idle_seconds=$(($(date +%s)-${last_handshake}))
  [ ${idle_seconds} -lt 150 ] && return 0;
  logger -t "amneziawg_monitor" "${iface} 的端点 ${endpoint_host}:${endpoint_port} 已有 ${idle_seconds} 秒无响应，正在尝试重新解析主机名"
  awg set "${iface}" peer "${public_key}" endpoint "${endpoint_host}:${endpoint_port}"
}

# 通过 ubus 查询所有活动的 AmneziaWG 接口
awg_ifaces=$(ubus -S call network.interface dump | jsonfilter -e '@.interface[@.up=true]' | jsonfilter -a -e '@[@.proto="amneziawg"].interface' | tr "\n" " ")

# 检查每个活动 AmneziaWG 接口中的所有对端
config_load network
for iface in $awg_ifaces; do
  config_foreach check_peer_activity "amneziawg_${iface}" "${iface}"
done
